apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  clusterIP: None  # This makes it a headless service
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017