apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx2
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
              - key: disktype
                operator: In
                values:
                  - hdd
