apiVersion: v1
kind: Pod
metadata:
  name: critical-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "512Mi"
        cpu: "15000m"
  priorityClassName: high-priority
