# This is a sample pod yaml

apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']